### ISSUE TITLE
Building generator not working in 2017.4.0f1 Personal

### ISSUE THREAD

**Issue by rgardler** [Syomus/ProceduralToolkit#31] opened 2018-05-09 02:36 UTC
The building generator is producing lots of noise as can be seen in the image below.

![image](https://user-images.githubusercontent.com/250240/39792585-3048a90a-52f6-11e8-8a4c-c96553043c37.png)

## Bug report

Building generator is creating correct size buildings but they are not neatly rendered.

### Version
* Unity: 2017.4.0f1 Personal
* ProceduralToolkit: 0.2.0 (installed from asset store)

### Steps to reproduce

  1. Open Buildings scene
  2. Scene looks OK in the editor
  3. Hit play
  4. Generated building looks like the image above (in both Game window and Editor window)
  5. Adjusting parameters changes building  correctly by length, width, floors etc. but similar issues are seen in all cases

## Feature request

Behaviour as seen at http://syomus.com/ProceduralToolkit/Buildings is the goal

## Question

Depending on whether I find something else suitable I may be willing to try to debug this. However, I'm no Unity expert and have not looked at the code here yet. Any pointers as to what might be wrong will help me (or someone else) should I decide to take a look.

**Comment by rgardler** [comment] 2018-05-09 02:40
I've taken a look at a bunch of the other scenes. They seem to work fine.

**Comment by BasmanovDaniil** [comment] 2018-05-09 09:59
Thank you for the bug report! There was an issue in CompoundMeshDraft which was fixed but not pushed yet into the Asset Store. You can either replace the file with a [fixed version](https://github.com/Syomus/ProceduralToolkit/blob/master/Scripts/CompoundMeshDraft.cs) or install a newer version of the toolkit from the repository.

**Comment by BasmanovDaniil** [comment] 2018-05-09 10:48
I've uploaded fixed packages to the [release page](https://github.com/Syomus/ProceduralToolkit/releases/tag/0.2.0) and submitted them to the Asset Store, hopefully they will be approved soon.

**Comment by BasmanovDaniil** [comment] 2018-05-09 10:52
Duplicate of #13

**Comment by BasmanovDaniil** [comment] 2018-05-11 20:39
New packages are on the Asset Store

**Closed by BasmanovDaniil** 2018-05-11 20:39 UTC
Labels: bug, duplicate
